/*
 * LCD.h
 *
 * Created: 3/5/2023 11:41:41 PM
 *  Author: 20100
 */ 


#ifndef LCD_H_
#define LCD_H_
#include "DIO.h"
#include "LCD_Confg.h"
//////////COMMANDS////////////////

#define CLR_SCREEN 0X01						//bms7 kol ela 3la LCD 
#define RETURN_HOME 0X02					//BYRG3 EL --CURSOR-- 3ND AWL 5ANA WMOMKN AKTB FEHA 
   //ENTRY MODE COMMAND//
#define SHIFT_CURSOR_TO_LEFT 0X04			//SHIFT --CURSOR-- LEFT M3 KOL 7ARF BKTBO "MN8ER MKTB MFESH SHIFT"
//#define SHIFT_DISPLAY_TO_RIGHT 0X05			//SHIFT --DISPLAY-- RIGHT M3 KOL 7ARF BKTBO "MN8ER MKTB MFESH SHIFT"
#define SHIFT_DISPLAY_TO_LEFT 0X07			//SHIFT --DISPLAY-- LEFT M3 KOL 7ARF BKTBO "MN8ER MKTB MFESH SHIFT"
#define ENTRY_MODE 0X06						//LAMA AKTB 7ARF BY3ML SHIFT LEL --CURSOR-- RIGHT
  //DSIPLAY ON/OFF CONTROL//
#define DISPLAY_ON_CURSOR_OFF 0X0C			//BY5FE EL --CURSOR-- Y5TFE
#define DISPLAY_ON_CURSOR_ON 0X0E			//BY5LE EL --CURSOR-- YZHAR ASLUN
#define DISPLAY_ON_CURSOR_BLINK 0X0F		//BY5LE EL --CURSOR-- YNWR W YTFE "BLINKING"
   //CURSOR OR DISPLAY SHIFT//
#define SHIFT_CURSOR_POSITION_LEFT 0X10		//SHIFT --CURSOR-- LEFT "MSH LAZM MKTB HAGA ZAE COMMAND EL FO2"   //WM3AK AVILABLE MN 0X10 L7D 0X13
#define SHIFT_CURSOR_POSITION_RIGHT 0X14	//SHIFT --CURSOR-- RIGHT "MSH LAZM AKTB HAGA ZAE COMMAND EL FO2" //WM3AK AVILABLE MN 0X14 L7D 0X17
#define ENTIRE_DESPLAY_TO_LEFT 0X18			//SHIFT --DISPLAY-- LEFT "MSH LAZM AKTB HAGA ZAE COMMAND EL FO2" AVILABLE MN 0 LHAD 40 DECIMAL 
#define ENTIRE_DESPLAY_TO_RIGHT  0X1C		//SHIFT --DISPLAY-- RIGHT "MSH LAZM AKTB HAGA ZAE COMMAND EL FO2" AVILABLE MN 64 LHAD 103 DECIMAL 

///////////////////////////////////
#define PORTNAME 'A' 

#if defined four_bits_mode 
#define EN 0								// DOL 3LA HSB TWSLTE M3 EL MICROCONTROLLER MSLN ANA MWSLHOM  
#define RS 1
#define RW 2								// 3LA PORT B AWL W TANY W TALT PIN

#define FOUR_BITS 0X028

#elif defined eight_bits_mode
#define EN 0								// DOL 3LA HSB TWSLTE M3 EL MICROCONTROLLER MSLN ANA MWSLHOM
#define RS 1								// 3LA PORT B AWL W TANY W TALT PIN
#define RW 2
#define EIGHT_BITS 0X038
#endif

void LCD_vInt(void);
static void send_falling_edge(void);
void LCD_vSend_cmd(char cmd);
void LCD_vSend_char(char data);
void LCD_vSend_String(char *data);
void LCD_vClearScreen(void);
void LCD_vMove_Cursor(char row , char coloumn);

#endif										/* LCD_H_ */